### ISSUE TITLE
Release 1.2.0 F-Droid continually crashes after upgrade from 1.1.2

### ISSUE THREAD

**Issue by dnaod** [jkuester/unlauncher#85]
After updating to the new F-Droid release of 1.20, Unlauncher does not open, keeps stopping, and is unusable.

Pixel3a
Android 11 latest security update

Steps to reproduce:

1. Press home
2. Choose either Once or Always at "Use Unlauncher as Home"

Expected  Result:
Unlauncher is opened as the homepage

Actual Result:
Alternating blank white and black screen flashing before stock Android "Unlauncher keeps stopping" screen eventually appears.

Steps taken:
- reboot
- downgrade to 1.1.2 (fails)

**Comment by dnaod** [comment]
Further steps taken:
- Clearing data and opening (same result as reported)
- Clearing data, uninstalling, and reinstalling from F-Droid. (same result as reported)

**Comment by dnaod** [comment]
Uninstalling completely and installing (prevoius version) 1.1.2 from F-Droid successfully got me back up and running.

**Comment by jweickm** [comment]
I had the exact same issue on a Samsung Galaxy S10. Also downgrading restored the functionality.

**Comment by CPacaud123** [comment]
Exact same behavior and workaround here. Teracube 2e, Android 10.

**Comment by Donkey-Doug** [comment]
Same.

**Comment by jkuester** [comment]
Well this is really worst case scenario. :disappointed: I have no idea why the apk from F-Droid would crash when the apk that I build locally works fine...

For now, all I can say is DO NOT UPDATE to 1.2.0!  I am going to work on pushing a new version (to either fix or revert the changes) but unfortunately, the delay in F-Droid publishing means it will not be out on the repo for at least a few days.  

For the record, here are the logs I am seeing when the apk from F-Droid crashes: 
```
09-30 10:50:43.560   770  2945 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.jkuester.unlauncher cmp=com.jkuester.unlauncher/com.sduduzog.slimlauncher.MainActivity} from uid 10138
09-30 10:50:43.617   770   770 V SettingsProvider: Notifying for 0: content://settings/secure/reminder_exp_learning_time_elapsed
09-30 10:50:43.634   359   359 D Zygote  : Forked child process 9182
09-30 10:50:43.638   770   806 I ActivityManager: Start proc 9182:com.jkuester.unlauncher/u0a196 for pre-top-activity {com.jkuester.unlauncher/com.sduduzog.slimlauncher.MainActivity}
...
09-30 10:50:44.394  9182  9182 E AndroidRuntime: FATAL EXCEPTION: main
09-30 10:50:44.394  9182  9182 E AndroidRuntime: Process: com.jkuester.unlauncher, PID: 9182
09-30 10:50:44.394  9182  9182 E AndroidRuntime: java.lang.RuntimeException: Field apps_ for g.c.a.a.c not found. Known fields are [public g.b.a.z$c g.c.a.a.c.k, public static final g.c.a.a.c g.c.a.a.c.i, public static volatile g.b.a.x0 g.c.a.a.c.j]
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at g.b.a.s0.K(Unknown Source:62)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at g.b.a.s0.y(:6)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at g.b.a.s0.x(Unknown Source:12)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at g.b.a.z0.a(:35)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at g.b.a.z0.b(Unknown Source:4)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at g.b.a.x.hashCode(:2)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at f.i.d.o.e(:2)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at f.i.d.o.f(Unknown Source:60)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at f.i.d.o.c(:8)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at f.i.d.o$e.e(:4)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at f.i.d.o$e.t(:2)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at f.i.d.n$b.e(:8)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at j.l.j.a.a.n(:2)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at k.a.o0.run(:4)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at k.a.h2.a.i(Unknown Source:0)
09-30 10:50:44.394  9182  9182 E AndroidRuntime: 	at k.a.h2.a$a.run(:7)
09-30 10:50:44.400   770  9215 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
09-30 10:50:44.401   770  2945 W ActivityTaskManager:   Force finishing activity com.jkuester.unlauncher/com.sduduzog.slimlauncher.MainActivity
09-30 10:50:44.405   770  9215 W DropBoxManagerService: Dropping: data_app_crash (789 > 0 bytes)
09-30 10:50:44.423   770   795 I ActivityManager: Showing crash dialog for package com.jkuester.unlauncher u0
09-30 10:50:44.427   770   805 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-30 10:50:44.428   770   805 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-30 10:50:44.606  1215  1229 I ndroid.systemu: NativeAlloc concurrent copying GC freed 482(69KB) AllocSpace objects, 0(0B) LOS objects, 49% free, 12MB/24MB, paused 80us total 183.969ms
09-30 10:50:44.901   770   797 W ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{1495a36 u0 com.jkuester.unlauncher/com.sduduzog.slimlauncher.MainActivity t106 f}
09-30 10:50:44.918   770   797 W ActivityTaskManager: Activity pause timeout for ActivityRecord{1495a36 u0 com.jkuester.unlauncher/com.sduduzog.slimlauncher.MainActivity t106 f}
...
```

Unfortunately, my initial review of those logs does not really give me any insights into the issue.

**Comment by jweickm** [comment]
@jkuester, 
thanks for responding to this so quickly. I hope it can be solved without much additional work on your end. Really happy with the launcher though; I appreciate your efforts!
Cheers, j

**Comment by CPacaud123** [comment]
Same here, loving Unlauncher ! Don't hesitate if there's anything I can help you with to isolate the problem.

**Comment by jimishol** [comment]
I had to uninstall and downgrade to 1.1.2 from fdroid. I have galaxy A6.  I hope when bug is fixed the version not to be 1.2.0 again, so as not to have a serries of tries and fails with current version again.
Having said that, I thank you very much for this wonderfuly simple launcher. Congratulations!!

**Comment by jkuester** [comment]
Okay, so after more investigation, it appears that something went wrong with auto-generating the new Proto data store classes [as part of the Gradle build](https://github.com/jkuester/unlauncher/blob/719a84b2c8b34e70ba5251dca7fd40e8d6396b34/app/build.gradle.kts#L105) or maybe those auto-generated classes are not being packaged correctly in the production APK.  

Either way, the fix is not obvious and will probably take some time and experimentation to sort out.  With this in mind, I have just pushed out a [v1.2.1](https://github.com/jkuester/unlauncher/releases/tag/v1.2.1) tag that simply rolls back all the changes from v1.2.0 (and should take the app back to the same state as the last release (v1.1.2)).  Unfortunately, that will probably take several days before it is published in F-Droid, so at this moment, down-grading back to v1.1.2 is still the best option.

Going forwards I intend to implement #86 before the next release which should help avoid this situation in the future by letting us publish beta versions of a release that do not trigger F-Droid to auto-update.  Once the process for beta versions is in place I will look at getting all of the changes from v1.2.0 worked back into a new (v1.3.0) release (that will be beta tested) and we can keep moving forward with development.  

I apologize for the inconvenience here and thank everyone for their patience as this gets sorted out!
